version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node.dev
    container_name: xboxdvr-node
    volumes:
      - ./NodeJS:/home/app
      - ./.vscode-server:/home/node/.vscode-server